name = "newsnow"
type = "javascript"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "4ca8e9fa-4093-4050-8d07-fa5c6d087e85"
